import { HeaderJa } from '@/components/header-ja'
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import type { ReactNode } from 'react'
import '../globals.css'
import { Noto_Sans_JP } from 'next/font/google'

const notoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: ReactNode
  params: Promise<{ language: string }>
}

export default async function RootLayout({ children, params }: Props) {
  const { language } = await params
  if (language !== 'en' && language !== 'ja') notFound()

  return (
    <html lang={language}>
      <body className={`${notoSansJp.variable} font-notoSansJp`}>
        {language === 'ja' && <HeaderJa />}
        <main className="relative min-h-[200vh]">{children}</main>
      </body>
    </html>
  )
}
