import { HeaderJa } from '@/components/header-ja'
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import type { ReactNode } from 'react'
import '../globals.css'
import { HeaderEn } from '@/components/header-en'
import { Noto_Sans_JP, Roboto } from 'next/font/google'
import { twMerge } from 'tailwind-merge'

const notoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: ReactNode
  params: Promise<{ language: string }>
}

export default async function RootLayout({ children, params }: Props) {
  const { language } = await params
  if (language !== 'en' && language !== 'ja') notFound()

  return (
    <html lang={language}>
      <body
        className={twMerge(
          `${notoSansJp.variable}  ${roboto.variable}`,
          language === 'ja' ? 'font-notoSansJp' : 'font-roboto',
        )}
      >
        {language === 'ja' && <HeaderJa />}
        {language === 'en' && <HeaderEn />}
        <main className="relative bg-zinc-100">{children}</main>
      </body>
    </html>
  )
}
